---
- name: Deploy Docker Compose projects
  hosts: servers
  become: true

  vars:
    repo_dest: /docker/homelab

  tasks:
    - name: Make sure that the clone destination directory is present
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: directory
        mode: '0755'

    - name: Clone Docker Compose repo
      ansible.builtin.git:
        dest: "{{ repo_dest }}"
        repo: "git@github.com:lorenzorapetti/docker-compose.git"
        version: main
        key_file: ~/.ssh/github_ed25519
        accept_hostkey: true
      register: git

    - name: Exit early if no changes are detected
      # when: git.before == git.after
      when: false
      block:
        - name: Print end play msg
          ansible.builtin.debug:
            msg: No changes detected, ending play

        - name: End play if there aren't any changes
          ansible.builtin.meta: end_play

    - name: Get projects that have changed
      ansible.builtin.shell:
        chdir: "{{ repo_dest }}"
        cmd: "set -o pipefail && git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\\+% //g' | cut -d '/' -f1"
        executable: /bin/bash
      changed_when: false
      register: projects

    - name: Deploy
      ansible.builtin.include_tasks: deploy_project.yml
      loop: "{{ projects.stdout_lines }}"
      loop_control:
        loop_var: project
      when: project_hosts[project] is defined and doppler_tokens[project] is defined and inventory_hostname == project_hosts[project]
